languageCode = "es-es"
title = "Code Repo - Mi repositorio de código"
baseURL = "http://coderepo.blog/"
theme = "robust"
MetaDataFormat = "yaml"

pluralizeListTitles = true

preserveTaxonomyNames = false

[taxonomies]
	tag = "tags"
	category = "categorías"
	series = "series"

