DefaultContentLanguage = "es"
title = "Code Repo - Mi repositorio de código"
baseURL = "http://www.coderepo.blog/"
theme = "robust"
MetaDataFormat = "yaml"

googleAnalytics = "UA-92982846-1"

disqusShortName = "www-coderepo-blog"

pluralizeListTitles = true

preserveTaxonomyNames = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "vs"

[taxonomies]
	tag = "tags"

[params.author]
    # If you want to display author information set these
    # This is Optional values
    name = "Miguel Veloso"

    description1 = "Independent Software Consultant"
    description2 = "Certified ScrumMaster"

    # Please set account ids
    # This is Optional values
    twitter  = "https://twitter.com/mvelosop"
    linkedin = "https://www.linkedin.com/in/miguelvelosop/?locale=en_US"
    github   = "https://github.com/mvelosop"
    email    = "mailto:mvelosop@gmail.com"
