languageCode = "es-es"
title = "Code Repo - Mi repositorio de código"
baseURL = "http://coderepo.blog/"
theme = "robust"
MetaDataFormat = "yaml"

pluralizeListTitles = true

preserveTaxonomyNames = false

[taxonomies]
	tag = "tags"
	category = "categorías"
	series = "series"

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Miguel Veloso"

    # Please set account ids
    # This is Optional values
    twitter  = "mvelosop"
    linkedin = "miguelvelosop"
    github   = "mvelosop"
    email    = "mvelosop@gmail.com"
